config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new show create]
  resource :sessions, only: %i[new create destroy]
  resources :events
  post "user/add-event",to: "tickets#create", as: "user_add_event"
  delete "event/unregister", to: "tickets#destroy", as: "destroy_event"
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: :User
  has_many :tickets
  has_many :attendees, through: :tickets, source: :user

  scope :previous, -> { where('start < ?', Time.now) }
  scope :upcoming, -> { where('start >= ?', Time.now) }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # validates :password, confirmation: true, presence: true
  # validates :password_confirmation, presence: true

  has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }
  has_many :organized_events, foreign_key: :creator_id, class_name: :Event
  has_many :tickets
  has_many :attended_events, through: :tickets, source: :event

  def attending?(event_id)
    tickets.where(event_id: event_id).exists?
  end

  def register(event_id)
    tickets.create(event_id: event_id)
  end

  def unregister(event_id)
    tickets.find_by(event_id: event_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  helper_method :user_signed_in?

  def authorize
    redirect_to new_sessions_path unless current_user
  end

  def user_signed_in?
    return true if session[:user_id] and session[:user_id] == current_user.id and current_user != {}

    false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authorize, except: %i[index]

  def index
    @upcoming_events = Event.upcoming
    @previous_events = Event.previous
  end

  def show
    @attendees = @event.attendees
    print @attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.organized_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :start, :end)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user_credentials = Credentials.new('example@gmail.com', '')
  end

  def create
    keys = params[:user]
    email = keys[:email]
    user = User.find_by_email(email)

    if user&.authenticate(keys[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:alert] = "User doesn't exits on the database"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_sessions_path
  end
end

class Credentials
  attr_reader :email, :password

  def initialize(email, password)
    @email = email
    @password = password
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    new_ticket = current_user.tickets.build(event_id: params[:id])
    if new_ticket.save
      redirect_to events_path, notice: 'Successfully added the event'
    else
      flash.now[:alert] = 'Server Error'
      redirect_to events_path
    end
  end

  def destroy
    redirect_back fallback_location: users_path if current_user.unregister(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    user = User.find(params[:id])
    @upcoming_events = user.attended_events.upcoming
    @previous_events = user.attended_events.previous
    @user_events = user.organized_events
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password_confirmation, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-4 col-xl-5 col-md-7 col-sm-9 col-12 shadow border-rounded pt-3 mx-auto ">
      <h2 class="text-center"> <%= form_heading %></h2>
      <%= simple_form_for(event, as: 'event', method: :post, url: events_path) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :title,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Title" }%>
          <%= f.input :description,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Description" }%>

          <%= f.input :start, label: 'Start Date:',
placeholder: 'i.e 20-5-2020',
            as: :string, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year]%>
          <%= f.input :end, label: 'End Date:', as: :string, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year]%>
        </div>

        <div class="form-actions">
          <%= f.button :submit,  form_submit, class: 'btn btn-info' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <ul class="col-6">
      <h4 class ="text-uppercase">Upcoming events</h4>
      <% @upcoming_events.each do |event| %>
        <div class="shadow py-2 my-2">
          <div class="d-flex flex-column ml-3">
            <h6 class="text-uppercase"><%= event.title%></h6>
            <p><%= event.description%></p>
          </div>
          <div class=" ml-2 d-flex flex-column ">
            <strong>Start: <%= event.start%></strong>
            <strong>End: <%= event.end%></strong>
          </div>
          <%if user_signed_in? %>
            <%if  current_user.attending?(event.id)%>
            <span>Attending</span>
          <%else%>

          <%= link_to 'Attend', user_add_event_path(id:event.id), method: :post %>
        <%end%>
        <% end  %>
        </div>
      <% end %>
    </ul>
    <ul class="col-6">
      <h4 class="text-uppercase">Previous events</h4>
      <% @previous_events.each do |event| %>
        <div class="shadow py-2 my-2">
          <div class="d-flex flex-column ml-3">
            <h6 class="text-uppercase"><%= event.title%></h6>
            <p><%= event.description%></p>
          </div>
          <div class=" ml-2 d-flex flex-column ">
            <strong>Start: <%= event.start%></strong>
            <strong>End: <%= event.end%></strong>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form', event: @event, form_heading: 'Create Event', form_submit: 'Submit'%>

app/views/events/show.html.erb
<div class="container">
  <h2 class="text-center text-bolder">Event's Info Page</h2>
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="shadow py-2 my-2 ">
        <div class="d-flex flex-column ml-3">
          <h4 class="text-uppercase"><%= @event.title%></h4>
          <p><%= @event.description%></p>
        </div>
        <div class=" ml-2 d-flex flex-column ">
          <strong>Start: <%= @event.start%></strong>
          <strong>End: <%= @event.end%></strong>
        </div>
      </div>
      <h6>Attendees</h6>
      <% @attendees.each_with_index do |user, idx| %>
        <p><%= (idx + 1).to_s  + ". " + user.first_name + " " + user.last_name%></p>
      <% end %>
      <%=link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-4 col-xl-5 col-md-7 col-sm-9 col-12 shadow border-rounded pt-3 mx-auto ">
      <h2 class="text-center"> <%= form_heading %></h2>
      <%= simple_form_for(@user, as: :user, method: :post, url: users_path) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :first_name,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "First Name" }%>
          <%= f.input :last_name,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Last Name" }%>
          <%= f.input :email,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "email" }%>
          <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
        </div>

        <div class="form-actions">
          <%= f.button :submit,  form_submit, class: 'btn btn-info' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= render 'form', user: @user, form_heading: 'Sign up', form_submit: 'Submit'%>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <ul class="col-3">
        <h4>Previous events</h4>
        <% @previous_events.each do |event| %>
          <li class="shadow py-2 my-2">
            <div class="d-flex flex-column ml-3">
              <h4 class="text-uppercase"><%= event.title%></h4>
              <p><%= event.description%></p>
            </div>
            <div class=" ml-2 d-flex flex-column ">
              <strong>Start: <%= event.start%></strong>
              <strong>End: <%= event.end%></strong>
            </div>
          </li>
        <% end %>
      </ul>
      <ul class="col-6 text-center">
        <h4>My Events</h4>
        <% @user_events.each do |event| %>
          <li class="shadow py-2 my-2">
            <div class="d-flex flex-column ml-0">
              <h6 class="text-uppercase">
                <%=link_to event.title, event_path(event)%>
              </h6>
            </div>
            <div class=" ml-2 d-flex  ">
              <strong>Start: <%= event.start%></strong>
              <strong>End: <%= event.end%></strong>
            </div>
          </li>
        <% end %>
      </ul>

      <ul class="col-3">
        <h4>Upcoming events</h4>
        <% @upcoming_events.each do |event| %>
          <li class="shadow py-2 my-2">
            <div class="d-flex flex-column ml-3">
              <h4 class="text-uppercase"><%= event.title%></h4>
              <p><%= event.description%></p>
            </div>
            <div class=" ml-2 d-flex flex-column ">
              <strong>Start: <%= event.start%></strong>
              <strong>End: <%= event.end%></strong>
            </div>
            <%if current_user.attending?(event.id)%>
            <%= link_to "cancel", destroy_event_path(id:event.id), method: :delete %>
          <% end %>
          </li>
        <% end %>
      </ul>

    <% end %>
    </ul>
  </div>
</div>